Medicare/Models/ViewModels/AdminEditViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Medicare.Models.ViewModels
{
    public class AdminEditViewModel
    {
        public User User { get; set; }

        public List<BloodType> BloodTypes { get; set; }
        public List<Specialization> Specializations { get; set; }
    }
}

Medicare/Controllers/DoctorsController.cs
using Medicare.Models;
using Medicare.Models.ViewModels;
using Syncfusion.Pdf;
using Syncfusion.Pdf.Grid;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Medicare.Controllers
{
    public class DoctorsController : Controller
    {
        ApplicationDatabase database = new ApplicationDatabase();

        protected override void Dispose(bool disposing)
        {
            database.Dispose();
        }

        // GET: Doctors
        public ActionResult Index()
        {
            //if(!SessionHandler.IsUserAdmin(Session))
            return View();
        }



        public ActionResult View(int? id)
        {
            if (!id.HasValue)
            {
                id = 0;
            }

            User doctor = database.Users.Include(d => d.Specialization).Where(d => d.IsDoctor && d.Id == id).SingleOrDefault();
            return View(doctor);
        }        
        
        public ActionResult Delete(int? id)
        {
            if (SessionHandler.IsUserAdmin(Session))
            {
                User user = database.Users.SingleOrDefault(d => d.Id == id);
                if (user != null)
                {
                    database.Users.Remove(user);
                    database.SaveChanges();
                }
                return RedirectToAction("doctors", "admin");


            }
            return RedirectToAction("","dashboard");
        }


        public ActionResult AdminEdit(int? id)
        {
            if (!id.HasValue)
            {
                id = 0;
            }

            User doctor = database.Users.Include(d => d.Specialization).Where(d => d.IsDoctor && d.Id == id).SingleOrDefault();
            List<Specialization> specializations = database.Specializations.ToList();
            return View(
                new AdminEditViewModel
                {
                    User=doctor,
                    Specializations = specializations
                }
                );
        }
        public ActionResult Edit(int? id)
        {
            return View();
        }
        public ActionResult Save(User user)
        {
            User dbDoctor = database.Users.Single(d => d.Id == user.Id);
            if (SessionHandler.IsUserAdmin(Session))
            {
                dbDoctor.DoctorRegistration = user.DoctorRegistration;
                dbDoctor.SpecializationId = user.SpecializationId;
                database.SaveChanges();


                return RedirectToAction("doctors", "admin");

            }
            database.SaveChanges();
            return RedirectToAction("", "dashboard");
        }
        public ActionResult AuthSave(User doctor)
        {
            User dbDoctor = database.Users.Single(d => d.Id == doctor.Id);
            if (SessionHandler.IsUserAdmin(Session))
            {
                dbDoctor.DoctorRegistration = doctor.DoctorRegistration;
                dbDoctor.SpecializationId = doctor.SpecializationId;
                database.SaveChanges();


                return RedirectToAction("doctorAuth", "admin");

            }
            database.SaveChanges();
            return RedirectToAction("", "dashboard");
        }
        public ActionResult ViewPdf()
        {
            if (!SessionHandler.IsUserAdmin(Session)) return RedirectToAction("", "Dashboard");



            List<User> doctors = database.Users.Include(u => u.Specialization).Where(a => a.IsDoctor).ToList();

            PdfDocument document = new PdfDocument();
            PdfPage page = document.Pages.Add();
            PdfGrid pdfGrid = new PdfGrid();
            DataTable dataTable = new DataTable();
            dataTable.Columns.Add("    " + "Registration ID");
            dataTable.Columns.Add("    " + "Name");
            dataTable.Columns.Add("    " + "Gender");
            dataTable.Columns.Add("    " + "Email Address");
            dataTable.Columns.Add("    " + "Category");
            dataTable.Columns.Add("    " + "Status");
            foreach (User doctor in doctors)
            {
                dataTable.Rows.Add("    " + doctor.DoctorRegistration, "    " + doctor.Name, "    " + doctor.Gender, "    " + doctor.Email, "    " + doctor.Specialization.Name, "    " + doctor.DoctorRegistration == null ? "Unauthorized" : "Authorized");
            }
            pdfGrid.DataSource = dataTable;
            pdfGrid.Draw(page, new PointF(10, 10));
            document.Save("Output.pdf", HttpContext.ApplicationInstance.Response, HttpReadType.Save);
            document.Close(true);
            return View();
        }
    }
}

Medicare/Controllers/PatientsController.cs
using Medicare.Models;
using Medicare.Models.ViewModels;
using Syncfusion.Pdf;
using Syncfusion.Pdf.Grid;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Web.Helpers;
using System.Web.Mvc;

namespace Medicare.Controllers
{
    public class PatientsController : Controller
    {
        ApplicationDatabase database = new ApplicationDatabase();

        // GET: Patients
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult View(int? id)
        {
            if (!id.HasValue)
            {
                id = 0;
            }

            User patient = database.Users.Include(u => u.BloodType).Where(d => !d.IsDoctor && !d.IsAdmin && d.Id == id).SingleOrDefault();
            return View(patient);
        }

        public ActionResult AdminEdit(int? id)
        {
            if (!id.HasValue)
            {
                id = 0;
            }

            User user = database.Users.Include(d => d.BloodType).Where(d => !d.IsDoctor && d.Id == id).SingleOrDefault();
            List<BloodType> bloodTypes = database.BloodTypes.ToList();
            return View(
                new AdminEditViewModel
                {
                    User = user,
                    BloodTypes = bloodTypes
                }
                );
        }

        public ActionResult Save(User user)
        {
            User dbPatient = database.Users.Single(d => d.Id == user.Id);
            if (SessionHandler.IsUserAdmin(Session))
            {
                dbPatient.Address = user.Address;
                dbPatient.BloodTypeId = user.BloodTypeId;
                dbPatient.Gender = user.Gender;
                database.SaveChanges();


                return RedirectToAction("patients", "admin");

            }
            database.SaveChanges();
            return RedirectToAction("", "dashboard");
        }
        public ActionResult Delete(int? id)
        {
            if (SessionHandler.IsUserAdmin(Session))
            {
                User user = database.Users.SingleOrDefault(d => d.Id == id);
                if (user != null)
                {
                    database.Users.Remove(user);
                    database.SaveChanges();
                }
                return RedirectToAction("patients", "admin");


            }
            return RedirectToAction("", "dashboard");
        }

        public ActionResult ViewPdf()
        {
            if (!SessionHandler.IsUserAdmin(Session)) return RedirectToAction("", "Dashboard");
            List<User> patients = database.Users.Include(u => u.BloodType).Where(a => !a.IsDoctor && !a.IsAdmin).ToList();

            PdfDocument document = new PdfDocument();
            PdfPage page = document.Pages.Add();
            PdfGrid pdfGrid = new PdfGrid();
            DataTable dataTable = new DataTable();
            dataTable.Columns.Add("    " + "Name");
            dataTable.Columns.Add("    " + "Gender");
            dataTable.Columns.Add("    " + "Email Address");
            dataTable.Columns.Add("    " + "Date of birth");
            dataTable.Columns.Add("    " + "Blood type");

            foreach (User patient in patients)
            {
                string bloodtype = patient.BloodType == null ? "Not updated" : patient.BloodType.Name;
                string dob = patient.BirthDate == null ? "Not updated" : patient.BirthDate.Value.ToString("yyyy MMM dd");
                dataTable.Rows.Add("    " + patient.Name, "    " + patient.Gender, "    " + patient.Email, "    " + dob, "    " + bloodtype);
            }
            pdfGrid.DataSource = dataTable;
            pdfGrid.Draw(page, new PointF(10, 10));
            document.Save("Output.pdf", HttpContext.ApplicationInstance.Response, HttpReadType.Save);
            document.Close(true);
            return View();
        }

        
    }
}

Medicare/Views/Patients/AdminEdit.cshtml
@model Medicare.Models.ViewModels.AdminEditViewModel

@{
    ViewBag.Title = "Update patient";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/Dashboard">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="/Admin/Patients">Patients</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>
    </ol>
</nav>
<div class="container px-md-5 px-md-1">

    <div class="col-lg-6 mx-auto">

        <h2>Edit patient</h2>
        @if (Model == null)
        {
            <div class="alert alert-warning" role="alert">
                Patient not found
            </div>
        }
        else
        {



    <div>
        @using (Html.BeginForm("save", "patients"))
        {
            <div class="form-floating mb-3">
                @Html.TextBoxFor(m => m.User.Name, new { @class = "form-control ", placeholder = "Name", @readonly = "", disabled = "" })
                @Html.LabelFor(m => m.User.Name)
            </div>
            <div class="form-floating mb-3">
                @Html.TextBoxFor(m => m.User.Email, new { @class = "form-control ", placeholder = "Email address", @readonly = "", disabled = "" })
                @Html.LabelFor(m => m.User.Email)
            </div>
            <div class="form-floating mb-3">
                @Html.TextAreaFor(m => m.User.Address, new { @class = "form-control ", placeholder = "Address" })
                @Html.LabelFor(m => m.User.Address)
                @Html.ValidationMessageFor(m => m.User.Address)
            </div>
            <div class="mb-3">
                @Html.LabelFor(m => m.User.Gender)
                <div class="form-check form-check-inline">
                    @Html.RadioButtonFor(m => m.User.Gender, "Male", new { @class = "form-check-input mx-3", id = "gender-male" })
                    <label class="form-check-label" for="gender-male">Male</label>
                </div>
                <div class="form-check form-check-inline">
                    @Html.RadioButtonFor(m => m.User.Gender, "Female", new { @class = "form-check-input mx-3", id = "gender-female" })
                    <label class="form-check-label" for="gender-female">Female</label>
                </div>
            </div>
            <div class="form-floating mb-3">
                @Html.DropDownListFor(m => m.User.BloodTypeId, new SelectList(Model.BloodTypes, "Id", "Name"), "Select blood type", new { @class = "form-select" })
                @Html.LabelFor(m => m.User.BloodTypeId)
                @Html.ValidationMessageFor(m => m.User.BloodTypeId)

            </div>
            @Html.HiddenFor(m => m.User.Id)
            <button class="btn btn-primary mb-3 btn-lg w-100">Save</button>
        }
    </div>


        }
    </div>
</div>

Medicare/Views/Patients/View.cshtml
@model Medicare.Models.User
@{
    ViewBag.Title = "View patient";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/Dashboard">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="/Admin/Patients">Patients</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>
    </ol>
</nav>
<div class="container px-md-5 px-md-1">

    <div class="col-lg-6 mx-auto">

        <h2>View patient</h2>
        @if (Model == null)
        {
            <div class="alert alert-warning" role="alert">
                Patient not found
            </div>
        }
        else
        {

    <div>
        <div class="form-floating mb-3">
            @Html.TextBoxFor(u => u.Name, new { @class = "form-control ", placeholder = "Name", @readonly = "", disabled = "" })
            @Html.LabelFor(u => u.Name)
        </div>
        <div class="form-floating mb-3">
            @Html.TextBoxFor(u => u.Email, new { @class = "form-control ", placeholder = "Email address", @readonly = "", disabled = "" })
            @Html.LabelFor(u => u.Email)
        </div>
        <div class="form-floating mb-3">
            @Html.TextAreaFor(u => u.Address, new { @class = "form-control ", placeholder = "Address", @readonly = "", disabled = "" })
            @Html.LabelFor(u => u.Address)
        </div>
        <div class="form-floating mb-3">
            @Html.TextBoxFor(u => u.Gender, new { @class = "form-control ", placeholder = "Email address", @readonly = "", disabled = "" })
            @Html.LabelFor(u => u.Gender)
        </div>
        <div class="form-floating mb-3">
            <input type="text" class="form-control" id="specialization" placeholder="Specialization" readonly disabled value='@(Model.BloodType==null?"N/A":Model.BloodType.Name)'>
            <label for="specialization">Blood type</label>
        </div>

        @if (Medicare.Models.SessionHandler.IsUserAdmin(Session))
        {

            @Html.ActionLink("Edit", "AdminEdit", "Patients", new { id = Model.Id }, new { @class = "btn btn-lg w-100 btn-primary mb-2" })
            <button class="btn btn-danger button-confirm btn-lg w-100" data-title="Confirm delete" data-body="Are you sure you want to delete?" data-href="\doctors\delete\@Model.Id">Delete</button>

        }
        else if (Medicare.Models.SessionHandler.GetUserId(Session) == Model.Id)
        {
            @Html.ActionLink("Edit", "Edit", "Doctors", new { id = Model.Id }, new { @class = "btn btn-lg w-100 btn-primary mb-2" })

        }

    </div>


        }
    </div>
</div>

Medicare/Views/Patients/ViewBloodChart.cshtml
@model Chart
@{
    ViewBag.Title = "ViewBloodChart";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>ViewBloodChart</h2>

@{
    @Model.Write();

}